"""Generate a synthetic preset-name capture.

IMPORTANT: this fixture is built from the wire model documented in CLAUDE.md,
not from a Helix LT. It locks in current parser behaviour so a refactor cannot
silently break it, and it exercises the properties that broke upstream's
parser -- variable-length records, 2-character names, out-of-order arrival and
names straddling packet boundaries. It cannot confirm that the wire model is
correct. Only a capture recorded off real hardware (HELIX_RECORD=...) can do
that; drop those in tests/fixtures/ alongside this one.

Regenerate with:
    .venv/bin/python -m tests.make_synthetic_capture
"""
import json
import os
import random
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from utils.packet_recorder import FIXTURE_KIND, FIXTURE_VERSION

SETLIST = 2
PRESET_COUNT = 128
PAYLOAD_BYTES = 24
SHUFFLE_SEED = 20260822

OUTPUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'fixtures', 'synthetic_setlist2.jsonl')


def synthetic_names():
	"""128 names covering the length range that matters.

	Lengths cycle 2..16: the 2-character case is the one that desynchronised
	upstream's fixed 25-byte record window.
	"""
	names = []
	for slot in range(PRESET_COUNT):
		if slot == 25:
			names.append('TwoPrinces')
		elif slot == 127:
			names.append('Voice')
		else:
			length = 2 + (slot % 15)
			names.append(('P{}_abcdefghijklmnop'.format(slot))[:length])
	return names


def encode_entry(absolute_index, name):
	"""One list entry as it appears in the payload stream."""
	entry = [0x81, 0xcd, (absolute_index >> 8) & 0xff, absolute_index & 0xff]
	entry += [0x84, 0xcd, 0x00]
	entry += [0x6d, 0xa1 + len(name)]
	entry += [ord(c) for c in name]
	return entry


def packet_header(seq, payload_len):
	"""16-byte transport header matching the template in request_preset_names."""
	return [0x08, 0x01, 0x00, 0x18, 0xef, 0x03, 0x01, 0x10,
			0x00, seq & 0xff, 0x00, 0x04, payload_len & 0xff, 0x02, 0x00, 0x00]


def build_capture():
	names = synthetic_names()

	slots = list(range(PRESET_COUNT))
	random.Random(SHUFFLE_SEED).shuffle(slots)

	stream = []
	for slot in slots:
		stream.extend(encode_entry(SETLIST * PRESET_COUNT + slot, names[slot]))

	packets = []
	for offset in range(0, len(stream), PAYLOAD_BYTES):
		payload = stream[offset:offset + PAYLOAD_BYTES]
		seq = len(packets)
		packets.append(packet_header(seq, len(payload)) + payload)

	meta = {
		'kind': FIXTURE_KIND,
		'version': FIXTURE_VERSION,
		'synthetic': True,
		'note': 'Generated by tests/make_synthetic_capture.py from the CLAUDE.md wire model. NOT recorded from hardware.',
		'setlist': SETLIST,
		'expect': {
			'count': PRESET_COUNT,
			'no_placeholder': True,
			'strict_indexing': True,
			'names_by_index': {str(i): name for i, name in enumerate(names)},
		},
	}
	return meta, packets


def write_capture(path=OUTPUT):
	meta, packets = build_capture()

	directory = os.path.dirname(path)
	if directory and not os.path.isdir(directory):
		os.makedirs(directory, exist_ok=True)

	with open(path, 'w', encoding='utf-8') as fh:
		fh.write(json.dumps(meta) + '\n')
		for seq, packet in enumerate(packets):
			payload = bytes(bytearray(packet))
			fh.write(json.dumps({
				'seq': seq,
				't': 0.0,
				'ep': '0x81',
				'len': len(payload),
				'data': payload.hex(),
			}) + '\n')

	return path, len(packets)


if __name__ == '__main__':
	written, count = write_capture()
	print('Wrote {} packets to {}'.format(count, written))
